Added boost_system dependency
 to fix compilation issue:

/usr/bin/ld: CMakeFiles/arduino_simple.dir/src/arduino_simple.cc.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status